# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Для зависимостей в package.json (npm или yarn)
  - package-ecosystem: "npm" # Используйте "yarn" если вы используете yarn.lock вместо package-lock.json
    directory: "/"           # Корень репозитория, где находится package.json
    schedule:
      interval: "weekly"     # Проверять обновления раз в неделю
    open-pull-requests-limit: 5 # Максимум 5 открытых PR одновременно

  # Для GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
